version: '3.4'

services:
  web:
    image: docker-registry.dccn.nl:5000/calendar-web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
    volumes:
      - $APPDATA/Microsoft/UserSecrets/:/root/.microsoft/usersecrets/:ro